jobs:
  - job: 'BuildDockerImage'
    pool:
      vmImage: 'windows-2019'
    steps:
      - task: Docker@2
        inputs:
          containerRegistry: 'Docker'
          repository: 'davidhayes/grafana'
          command: 'build'
          Dockerfile: '**/Dockerfile'
          tags: |
            nanoserver$(NanoServerVersion)grafana$(grafanaVersion)
            latest
          arguments: '--build-arg nanoServerVersion=$(NanoServerVersion) --build-arg grafanaVersion=$(grafanaVersion)'
      - task: Docker@2
        inputs:
          containerRegistry: 'Docker'
          repository: 'davidhayes/grafana'
          command: 'push'
          tags: |
            nanoserver$(NanoServerVersion)grafana$(grafanaVersion)
            latest
